Repository pagopa/selfcare-onboarding-backend, pull requests merged in 2023-12, with the labels that each got.

#205 [SELC-3495] bugfix: add city, county, country fields to institutionOnboardingInfoResource
  app/src/main/resources/swagger/api-docs.json
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyRegistryProxyConnector.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/Institution.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/institutions/InstitutionInfo.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/registry_proxy/GeographicTaxonomies.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/registry_proxy/HomogeneousOrganizationalArea.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/registry_proxy/InstitutionProxyInfo.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/registry_proxy/OrganizationUnit.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyRegistryProxyConnectorImpl.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/client/PartyRegistryProxyRestClient.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/InstitutionMapper.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/RegistryProxyMapper.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/AooResponse.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/BillingDataResponse.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/GeographicTaxonomiesResponse.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/InstitutionResponse.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/ProxyInstitutionResponse.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/model/UoResponse.java
  connector/rest/src/main/resources/config/party-registry-proxy-rest-client.properties
  connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyRegistryProxyImplTest.java
  connector/rest/src/test/resources/stubs/party-process/mappings/createInstitution.json
  connector/rest/src/test/resources/stubs/party-process/mappings/createInstitutionUsingExternalId.json
  connector/rest/src/test/resources/stubs/party-process/mappings/getInstitutionBillingData_fullyValued.json
  connector/rest/src/test/resources/stubs/party-process/mappings/getInstitutionByExternalId_fullyValued.json
  core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
  core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/model/InstitutionData.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingInstitutionInfoMapper.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingMapper.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
Labels: OAS:Compatible

#208 retrieve location data correctly for non IPA institution
  core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
  core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
Labels: OAS:NoChanges

#211 ops: move /v1 from helm to controller
  app/src/main/resources/swagger/api-docs.json
  helm/pnpg/values-dev.yaml
  helm/pnpg/values-prod.yaml
  helm/pnpg/values-uat.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  helm/values.yaml
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/PnPGInstitutionController.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/ProductController.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenController.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/UserController.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/PnPGInstitutionControllerTest.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/ProductControllerTest.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenControllerTest.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/UserControllerTest.java
Labels: OAS:NoChanges

#212 [SELC-3452] feat: added V2 for new onboarding request
  app/src/main/resources/swagger/api-docs.json
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/PartyConnector.java
  connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImpl.java
  connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
  connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/PartyConnectorImplTest.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionService.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImpl.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
  core/src/test/java/it/pagopa/selfcare/onboarding/core/InstitutionServiceImplTest.java
  core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2Controller.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingMode.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionControllerTest.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionV2ControllerTest.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
Labels: OAS:Incompatible

#213 [SELC-3452] fix: mapper onboarding v2
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: OAS:NoChanges

#217 fix: map business name onboarding V2
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
  connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
Labels: OAS:NoChanges

#218 [SELC-3509] feat: using new endpoints V2 for Onboarding Process Verification
  app/src/main/resources/swagger/api-docs.json
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
  connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
  connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
  core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
Labels: OAS:Compatible

#219 [SELC-3607] Increase replicas - DEV
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
Labels: OAS:NoChanges

#220 [SELC-3493] feat: add new endpoint for onboarding process verification by admin
  app/src/main/resources/swagger/api-docs.json
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/api/OnboardingMsConnector.java
  connector-api/src/main/java/it/pagopa/selfcare/onboarding/connector/model/onboarding/OnboardingData.java
  connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImpl.java
  connector/rest/src/main/java/it/pagopa/selfcare/onboarding/connector/rest/mapper/OnboardingMapper.java
  connector/rest/src/test/java/it/pagopa/selfcare/onboarding/connector/OnboardingMsConnectorImplTest.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenService.java
  core/src/main/java/it/pagopa/selfcare/onboarding/core/TokenServiceImpl.java
  core/src/test/java/it/pagopa/selfcare/onboarding/core/TokenServiceImplTest.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2Controller.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/model/OnboardingRequestResource.java
  web/src/main/java/it/pagopa/selfcare/onboarding/web/model/mapper/OnboardingResourceMapper.java
  web/src/main/resources/swagger/swagger_en.properties
  web/src/test/java/it/pagopa/selfcare/onboarding/web/controller/TokenV2ControllerTest.java
Labels: OAS:Compatible

#221 ops: increment default timeout rest client
  helm/values.yaml
Labels: OAS:NoChanges

#222 Implement mapstruct mapper for InstitutionOnboardingInfoResource
  web/src/main/java/it/pagopa/selfcare/onboarding/web/controller/InstitutionController.java
Labels: OAS:NoChanges
